# Generated by Django 5.0.4 on 2024-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="заголовок")),
                ("slug", models.CharField(max_length=50, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="содержимое"),
                ),
                (
                    "image_ph",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/",
                        verbose_name="Изображение(превью)",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("views_counter", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
            },
        ),
    ]
