# Generated by Django 5.0.4 on 2024-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_blogpost_views_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
