# Generated by Django 5.0.4 on 2024-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_blogpost_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="slug"
            ),
        ),
    ]
