# Generated by Django 4.2 on 2024-06-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category"],
                "permissions": [
                    ("can_change_description", "Can change product description"),
                    ("can_change_category", "Can change product category"),
                    ("set_published_status", "Can change product published status"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
