# Generated by Django 4.2 on 2024-06-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": [
                    ("can_change_publication_sign", "Can change blog publication_sign")
                ],
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="publication_sign",
            field=models.BooleanField(default=True, verbose_name="признак публикации"),
        ),
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
